name: Test
on:
  pull_request:
    branches:
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        run: yarn install
      - name: Run Tests
        uses: mattallty/jest-github-action@v1.0.3
        run: yarn jest --coverage --json --outputFile=/home/runner/work/_actions/mattallty/jest-github-action/v1/dist/jest.results.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'npm run test'
          # Runs tests related to the changes since the base branch of your pull request
          # Default to false if not set
          changes-only: true
